### ISSUE TITLE
Platzhalter Mail

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#11]
Fordert man ein neues Passwort an, so erhält man folgende nutzlose Mail:

-----Ursprüngliche Nachricht-----
Von: post@ptabaden.ch [mailto:post@ptabaden.ch] 
Gesendet: Montag, 4. April 2016 23:06
An: L1 Albula leiter1@ptabaden.ch
Betreff: Logindaten für %organization_homepage%

Hallo %user_first_name%,

du erhälst deine Logindaten für %organization_homepage% .
Benutzername: %user_login_name%
Passwort: %variable1%

Das Passwort wurde automatisch generiert.
Du solltest es nach deiner Anmeldung auf %organization_homepage% in deinem Profil ändern.

Freundliche Grüsse
Die Webmaster

Auch ein Problem der Sprachdatei?

**Comment by jamiedee** [comment]
Ja, aber wäre bereinigt, sobald man die Seite neu installiert

**Comment by jamiedee** [comment]
und dadurch die db neu erstellt
