### ISSUE TITLE
iCal und RSS

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#12]
Ich finde bei den Daten den RSS Feed nicht mehr (wollte den ausschalten) und frage mich, ob dir die iCal Funktion nicht besser deaktivieren? Eine Fehlerquelle weniger, welche getestet werden will & kaum jemand braucht vermutlich?

**Comment by jamiedee** [comment]
die iCal-Funktion geht aber ganz gut. Besser wäre natürlich eine Möglichkeit, diesen direkt zu abonnieren mit autoupdate.

**Comment by sxwid** [comment]
okidoks, wenn du das getestet hast ist gut.
