### ISSUE TITLE
Fotoalbum Originale

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#13]
Ich hab noch die Option "Originale zusätzlich speichern" aktiviert, so erhalten wir die Fotos der Leiters auch noch in "guter" Qualität - damit wir die vielleicht für die Zukunft auch wieder irgendwo sichern können.... Ok für dich?

**Comment by jamiedee** [comment]
Nein, geht nicht weil wir nur 2 GB Speicherplatz haben und diese nur schon für die vorhandenen Fotos nicht ausreicht

**Comment by sxwid** [comment]
hm, ich meinte eigentlich erst ab 2016 oder so. und wenn da 20 aktivitäten mit 20 fotos à 1 MB sind, dann haben wir 400MB im Jahr und könnten so ca. 3 Jahre fahren. aber muss auch nicht umbidingt sein. nur weil ich damals den text eingeblendet hab. aber den haste ja nicht mehr drin. okidoks.

**Comment by jamiedee** [comment]
ja im prinzip wär das schon auch gut, weil wenn ganz verschiedene Leute Fotos machen, fehlt die Komplettsammlung. Aber ist schnell mal 4-5 MB pro Foto, auch vom Smartphone und dann sind wir in weniger als einem Jahr Speicherlos ;) Man könnt die Funktion mal aktivieren, nach dem ich alle hochgeladen hab. hab noch alle von 2014 - 2008 klar sortiert als Ordner, in guter Qualität und als Webversion. (Sind dann auch auf der PTA Festplatte von dir, welche du bestimmt im Sommer wieder zurück bekommst!)

**Comment by sxwid** [comment]
das finde ich einen gueten plan! :yes:

**Comment by sxwid** [comment]
das finde ich einen gueten plan! :yes:
