### ISSUE TITLE
Server killed by Domainnennung

### ISSUE THREAD

**Issue by jamiedee** [sxwid/admidio3.1_scoutversion#14]
Ich wollte bei meinem Profil meine Website abspeichern. Daraufhin ist alles explodiert. =D

Ich hab als Website meine Website mit https:// angegeben. liegt es daran?

![bildschirmfoto 2016-04-05 um 12 06 05](https://cloud.githubusercontent.com/assets/2400979/14276402/64e1d660-fb27-11e5-8e93-3a67b586e846.png)

**Comment by sxwid** [comment]
wo ist denn das her? von my.hostfactory? ich find die meldung nicht. hm. und das warst definitiv du, aber wo hast du https:// angegeben? statt http://www.ptabaden.ch?

**Comment by jamiedee** [comment]
ne ich hab in meinem Profil meine Website abspeichern wollen ;)
https://www.jeremydaepp.ch

und dann kam ne restricted meldung und dann haben sie uns blockiert wegen sicherheitsrisiko

![bildschirmfoto 2016-04-05 um 12 16 02](https://cloud.githubusercontent.com/assets/2400979/14276622/3c62dbd4-fb28-11e5-9d46-b79a8c4a9e23.png)

**Comment by jamiedee** [comment]
sorry, muss los: Mittag!

Aber dies ist der Error Log vom Hosting

[Tue Apr 05 10:58:40 2016] [error] [client 88.192.250.125] ModSecurity: Access denied with code 403 (phase 2). Match of "beginsWith %{request_headers.host}" against "TX:1" required. [file "/etc/apache2/modsecurity.d/rules/atomic/modsec/10_asl_rules.conf"] [line "502"] [id "340162"] [rev "300"] [msg "Atomicorp.com WAF Rules: URL detected as argument, possible RFI attempt detected"] [data "%TX:0,TX:1"] [severity "CRITICAL"] [hostname "ptabaden.ch"] [uri "/pta2019/adm_program/modules/profile/profile_save.php"] [unique_id "VwN@QD6SDVgAAFDGCqMAAAAE"]
[Tue Apr 05 10:58:48 2016] [error] [client 88.192.250.125] ModSecurity: Access denied with code 403 (phase 2). Match of "beginsWith %{request_headers.host}" against "TX:1" required. [file "/etc/apache2/modsecurity.d/rules/atomic/modsec/10_asl_rules.conf"] [line "502"] [id "340162"] [rev "300"] [msg "Atomicorp.com WAF Rules: URL detected as argument, possible RFI attempt detected"] [data "%TX:0,TX:1"] [severity "CRITICAL"] [hostname "ptabaden.ch"] [uri "/pta2019/adm_program/modules/profile/profile_save.php"] [unique_id "VwN@SD6SDVgAAAkakloAAAAG"]
[Tue Apr 05 11:00:30 2016] [error] [client 88.192.250.125] ModSecurity: Access denied with code 403 (phase 2). Match of "beginsWith %{request_headers.host}" against "TX:1" required. [file "/etc/apache2/modsecurity.d/rules/atomic/modsec/10_asl_rules.conf"] [line "502"] [id "340162"] [rev "300"] [msg "Atomicorp.com WAF Rules: URL detected as argument, possible RFI attempt detected"] [data "%TX:0,TX:1"] [severity "CRITICAL"] [hostname "ptabaden.ch"] [uri "/pta2019/adm_program/modules/profile/profile_save.php"] [unique_id "VwN@rj6SDVgAAGl2KIsAAAAK"]

**Comment by sxwid** [comment]
also du hostest deine website da? warum muss die denn https sein? soweit ich weiss ist auf dem hosting ssl nicht aktiviert, könnte das daran liegen? 
und im log ist aber nur vom ptabaden zeugs die rede, hier blicke ich nicht ganz durch. speziell wurde mit profile_save.php etwas hochgeladen, wo eine URL im anhang war und das wurde als RFI attempt (Remote File Inclusion) detektiert - hast du so etwas gemacht?

**Comment by sxwid** [comment]
könnte heute nami ca. bis 14.00 skypen, wollen wir das da schnell besprechen?

**Comment by jamiedee** [comment]
Ui jetzt bin ich grad in der uni am arbeiten und ist etwas ungünstig deshalb.

Nein das Problem nochmals:

Hier:
![bildschirmfoto 2016-04-05 um 13 25 14](https://cloud.githubusercontent.com/assets/2400979/14278756/00476dcc-fb32-11e5-8d8c-c27ad200fd99.png)

habe ich meine eigene Website eingetragen.
Weil ich schauen wollte, was damit passiert. Mein Webserver hat SSL, somit kein Problem. Sollte in Admidio diese ja lediglich diese als Link speichern. Aber anscheinend macht es dies auf eine fatale Art;)

Klar ich kann auch einfach www.jeremydaepp.ch angeben. Aber wenn jemand die Website-Adresse aus dem Browser kopiert, kommt auch das https auch gleich mit.

**Comment by jamiedee** [comment]
ich schau mal was bei der Spielwiese passiert mit https

**Comment by jamiedee** [comment]
ok auf der Spielwiese gehts. also irgendwo mit dem profile_save / edit liegt das problem. ich schau mal

**Comment by sxwid** [comment]
aaah jetzt verstehe ich :100: ok - ich schau auch mal. vermutlich hast du irgendwo beim cssen die html tags rausgenommen oder so... ich versuch mal die beiden zu vergleichen...

**Comment by jamiedee** [comment]
Der gesamte Modulordner vom Profil scheint keine relevante Änderung gegenüber der aktuellen Version von Admidio aufzuweisen. Muss wahrscheinlich wo anders liegen? Aber nur mit CSS kannst du unmöglich so was erzeugen.

Ich hab mir überlegt, dass evtl. etwas mit dem Profilfeldeintrag nicht stimmt (die Option URL). Ich check mal die DB durch, ob noch so Sprachfehler drin sind

![bildschirmfoto 2016-04-05 um 14 10 30](https://cloud.githubusercontent.com/assets/2400979/14279987/a9f1b39a-fb38-11e5-9a9a-7c5dacea36c1.png)

**Comment by sxwid** [comment]
naja, im schlimmsten fall nehmen wir das raus - ich mein wer von den kids hat schon eine eigene website - und für wen ist das relevant? :)

**Comment by sxwid** [comment]
und lustig, ich habs getestet ob es auch bei einem neuen user passiert (also gesamthaft neu erstellter user) passiert - ja, ich kriege einen 403 error, aber keine meldung im frontend von hostfactory. und auch keinen eintrag im log?

**Comment by sxwid** [comment]
und könnte aber auch sein, dass der hoster dafür verantwortlich ist, bzw eine sicherheitsrichtline von hostfactory? ich versuchs mal in der version ohne deine änderungen aber auf unserem server!

edit: bei unserer sauberen installation passiert das gleiche! das heisst, unser server hat einfach strengere richtlinien bezüglich speichern von url oder so?

**Comment by jamiedee** [comment]
ok, glaub aber nicht.

das sind die db felder. vielleicht findet sich was, wenn man nach den feldnamen sucht?

![bildschirmfoto 2016-04-05 um 14 24 39](https://cloud.githubusercontent.com/assets/2400979/14280222/293a8022-fb3a-11e5-8a4e-80fde221ec26.png)

**Comment by jamiedee** [comment]
für mich ists relevant! =D

**Comment by jamiedee** [comment]
haha ok

ja erst beim zweiten mal, als ichs versucht habe, hat hostfactory uns gesperrt. bei beiden malen kam die 403 meldung auf den schirm

**Comment by sxwid** [comment]
tsts, du kannst ja werbung machen auf der hauptseite... :) 
aus dem net:

> Der Webserver (auf dem die Website läuft) denkt, dass der vom Client (z.B. Ihr Webbrowser oder unser CheckUpDown-Roboter) gesendete Datenstrom korrekt war, aber der Zugriff auf die durch die URL identifizierte Ressource aus irgendeinem Grund verboten ist.
> 
> Dies zeigt ein grundlegendes Zugriffsproblem an, das evtl. schwierig zu lösen ist, da das HTTP-Protokoll dem Webserver erlaubt, diese Antwort zu geben, ohne einen Grund dafür zu liefern. Daher entspricht der 403-Fehler einem pauschalen 'NEIN' durch den Webserver - das keine weiteren Diskussionen erlaubt.

**Comment by jamiedee** [comment]
[Tue Apr 05 13:12:50 2016] [error] [client 85.1.138.37] ModSecurity: Access denied with code 403 (phase 2). Match of "beginsWith %{request_headers.host}" against "TX:1" required. [file "/etc/apache2/modsecurity.d/rules/atomic/modsec/10_asl_rules.conf"] [line "502"] [id "340162"] [rev "300"] [msg "Atomicorp.com WAF Rules: URL detected as argument, possible RFI attempt detected"] [data "%TX:0,TX:1"] [severity "CRITICAL"] [hostname "ptabaden.ch"] [uri "/pta2019/adm_program/modules/profile/profile_save.php"] [unique_id "VwOdsj6SDVgAABQzaxAAAAAL"]
[Tue Apr 05 13:13:40 2016] [error] [client 85.1.138.37] ModSecurity: Access denied with code 403 (phase 2). Match of "beginsWith %{request_headers.host}" against "TX:1" required. [file "/etc/apache2/modsecurity.d/rules/atomic/modsec/10_asl_rules.conf"] [line "502"] [id "340162"] [rev "300"] [msg "Atomicorp.com WAF Rules: URL detected as argument, possible RFI attempt detected"] [data "%TX:0,TX:1"] [severity "CRITICAL"] [hostname "ptabaden.ch"] [uri "/pta2019/adm_program/modules/profile/profile_save.php"] [unique_id "VwOd5D6SDVgAAAVKjtEAAAAA"]
[Tue Apr 05 13:22:02 2016] [error] [client 85.1.138.37] ModSecurity: Access denied with code 403 (phase 2). Match of "beginsWith %{request_headers.host}" against "TX:1" required. [file "/etc/apache2/modsecurity.d/rules/atomic/modsec/10_asl_rules.conf"] [line "502"] [id "340162"] [rev "300"] [msg "Atomicorp.com WAF Rules: URL detected as argument, possible RFI attempt detected"] [data "%TX:0,TX:1"] [severity "CRITICAL"] [hostname "ptabaden.ch"] [uri "/pta2016/adm_program/modules/profile/profile_save.php"] [unique_id "VwOf2j6SDVgAAAwol4YAAAAK"]

**Comment by jamiedee** [comment]
von dir

**Comment by sxwid** [comment]
ja ich hab auch ein zweites mal versucht :)

**Comment by jamiedee** [comment]
ja eben, und im error log stehts auch

**Comment by sxwid** [comment]
haha, es kommt erst, wenn man insgesamt 2 mal den fehler provoziert von der gleichen IP.
aber im ernst: meinst du nicht, das macht keinen sinn im profil - und deine website ist ja im public bereich schon notiert und das reicht? weil wie gesagt - für die "normalen" teilnehmer bringt die funktion keinen mehrwert - und vermutlich wollen die auch kein webdesign von dir :)
ich mach aber mal einen fred im admidio forum...

**Comment by jamiedee** [comment]
ne eigentlich wollte ich dort eh nichts hin tun. aber dachte mir, wenn wir schon so nen üblen fehler haben, müsste man das schon bearbeiten. sonst fügt man das in ein paar jahren wieder hinzu und alles explodiert wieder

**Comment by sxwid** [comment]
das stimmt ja prinzipiell.. ich hab jetzt mal beim admidio forum nachgefragt. aber im moment sind ja wir verantwortlich & wir wissen es jetzt :)
[Admidio](http://admidio.org/forum/viewtopic.php?f=3&t=7057&p=24139#p24139)

**Comment by jamiedee** [comment]
wahrscheinlich ists schon eher unser mist, vom mergen und so;)

**Comment by sxwid** [comment]
aber auf der installation wo nur meine sachen sind (siehe mein error vom Tue Apr 05 13:22:02 201) passierts auch - und da hab ich NUR die leiterfunktion eingebaut und das mail...

**Comment by jamiedee** [comment]
oh =D dann ists ja gut ;)
