### ISSUE TITLE
Teilnehmer und Leiter

### ISSUE THREAD

**Issue by jamiedee** [sxwid/admidio3.1_scoutversion#15]
![bildschirmfoto 2016-04-05 um 11 14 24](https://cloud.githubusercontent.com/assets/2400979/14280498/af52f3aa-fb3b-11e5-8732-69ebb81bf610.png)

ich kann zwar mich als Webmaster Leiter aktivieren, aber beim nächsten laden der Seite ists wieder weg. Spielt jetzt für mich als Webmaster keine Rolle, aber vielleicht passiert auch der Fehler bei normalen Benutzern?

**Comment by sxwid** [comment]
ist nicht wirklich relevant, weil ich sowieso die Leiterfunktion doof finde. Darum haben alle diese Checkbox "Leiter" im Profil. Diese wird ausgelesen beim 
- Eintragen für Termine
- Versand von Emails
- die isLeiter() Funktion

Die Rollen werden nur gebraucht, um Rechte zu vergeben, wie Fotoupload und Downloads und so. Und weil TN und Leiter sowieso verschiedene Rollen sind spielts keine Rolle :)

**Comment by jamiedee** [comment]
brauchst du dann diese beiden Spalten bei der Mitgliederzuordnung für Aktivitäten?

![bildschirmfoto 2016-04-05 um 14 49 26](https://cloud.githubusercontent.com/assets/2400979/14280793/add43794-fb3d-11e5-9b82-f890207b070e.png)

**Comment by sxwid** [comment]
ja, bei den aktivitäten schon, da wird die sortierung tn/leiter gemacht. aber wenn sie sich anmelden ist dafür nur die checkbox im profil relevant. chunsch drus? bizzli verwirrend, sorry
