### ISSUE TITLE
Start?

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#16]
was meinst du? wollen wir eine frische umgebung in eigener Datenbank aufsetzen vom github und dann starten mit der Migrierung (mal fotos und downloads und termine, benutzerdaten erst so kurz vorher als möglich)? :)

**Comment by jamiedee** [comment]
ja wäre noch gut. sonst mach ich immer alles doppelt. hab mal eine neue unter www.ptabaden.ch/pfaditrotzallembaden erstellt und mal paar Grundlagen eingestellt. Scheinbar funktioniert die Language-Datei ohne Probleme. Habe für 2008 und 2009 Fotos hochgeladen, wollt mal checken ob das dort gut funktioniert.

wir können ja noch die pta2019 verwenden für Trials und mit der /pfaditrotzallembaden versuchen mit korrekten Daten abzufüllen?

du hast das gleiche Konto wieder wie vorher;)

**Comment by sxwid** [comment]
huhu jamiedee, ich find das gut so - test und fixe umgebung. ehm, aber beim sts gibts noch nen datenbankfehler - und mein login geht nicht.

**Comment by jamiedee** [comment]
thats strange. Ich habe auch letztes mal deine mail und pw eingestellt, wie jetzt auch. aber ich glaub weil fürs pw ein popup aufspringt, speichert es den benutzernamen beim ersten mal nicht?

Ach ja beim History Modul und bei der Startpage musste ich auch letztes Mal in der DB die Tabellen kopieren von ner alten pta page version

**Comment by jamiedee** [comment]
hast du deine "neues pw e-mail" bekommen?

soll ich die datenbankfelder rüberkopieren direkt in der db?

**Comment by sxwid** [comment]
hm, das sollte aber nicht sein bei den modulen, die sollte es selber erstellen. aber jenu. kann ich dann mal noch fixen (oder nie). ja kopier doch rein. 
und ja, passwort hab ich - damit hatte ich auch schon mühe mit dem passwort / username zeugs. die haben da so "sicherheit" eingebaut, dass es nicht erlaubt ist, als webmaster passwörter zu ändern..
