### ISSUE TITLE
Schriftgrösse Downloadbereich

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#17]
![unbenannt](https://cloud.githubusercontent.com/assets/13117378/14308651/c0a9394c-fbd7-11e5-9f43-791e8c43b5aa.PNG)
imho ist die schrift im downloadbereich sehr gross & es wird unübersichtlich, wenn alles auf 2 zeilen dargestellt wird. meinst du die könnte etwas kleiner werden, zb wie die schrift beim menu "Neuer Ordner"?

**Comment by jamiedee** [comment]
Ja da hats auch noch anderes, dass ich weg haben will…

Infoicon weg
![bildschirmfoto 2016-04-06 um 11 28 44](https://cloud.githubusercontent.com/assets/2400979/14310483/c000a508-fbea-11e5-9759-68cf55656750.png)

![bildschirmfoto 2016-04-06 um 11 15 53](https://cloud.githubusercontent.com/assets/2400979/14310491/c872ad8a-fbea-11e5-88c0-02288d49559d.png)

**Comment by jamiedee** [comment]
Vorläufig so funktionierend. Evtl. Separate Mobile-Version noch erstellen > Milestone 1.5
