### ISSUE TITLE
E-Mail verfassen: Leiter und Teilnehmer-Checkbox unnötig

### ISSUE THREAD

**Issue by jamiedee** [sxwid/admidio3.1_scoutversion#2]
Beim verfassen einer neuen E-Mail ist noch versehentlich die Leiter- und Teilnehmer-Checkbox drin.

![bildschirmfoto 2016-04-03 um 13 49 36](https://cloud.githubusercontent.com/assets/2400979/14239931/4c7f004a-fa49-11e5-9d53-e101c51c84d5.png)

**Comment by sxwid** [comment]
Ist es möglich, das im CSS auszublenden? Weil ich hab bis jetzt keine Möglichkeit gefunden, das nur für Termine zu machen. Aber wenn nein dann mach ich mich noch auf die Suche...

**Comment by jamiedee** [comment]
Ist ausgeblendet. Hoffe nicht irgendwo, wo es auch benötigt wird.
–> Da Änderung im Theme Ordner ists nicht hier sichtbar
