### ISSUE TITLE
E-Mail-Kontaktsuche auch mittels Pfadiname

### ISSUE THREAD

**Issue by jamiedee** [sxwid/admidio3.1_scoutversion#29]
Man kann im E-Mail-Adressfeld nur nach Vor- und Nachnamen suchen. Pfadiname wäre natürlich praktischer, sonst muss ich mir jedes Mal überlegen, dass du ja Simon heissen tust;)

Only if not to complicated. And no hurry. It's a detail

![bildschirmfoto 2016-04-26 um 09 52 53](https://cloud.githubusercontent.com/assets/2400979/14809327/f32d3b4e-0b94-11e6-8a33-d357c01b4141.png)

**Comment by sxwid** [comment]
fixed in commit c72aad54b78464f970ba3fc66e56d365b785e8d4
