### ISSUE TITLE
fucked up layout in mobile view

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#32]
![Uploading Screenshot_2016-08-26-20-51-53.png…]()
![Uploading Screenshot_2016-08-26-20-52-41.png…]()
![Uploading Screenshot_2016-08-26-20-56-12.png…]()
![Uploading Screenshot_2016-08-26-20-56-52.png…]()
teilweise lustige sonderzeichen, überall jedoch fehlendes menusymbol oben rechts. unter android default browser, lightning und opera mini.

**Comment by jamiedee** [comment]
Hey sxwid
Opera Mini ist ein Browser für Drittweltländer mit beschränktem Internetzugang. Das Internet wird aber auch dort immer besser. Jedenfalls ist das Grundprinzip des Browsers, möglichst wenige Daten zu verbrauchen und deshalb sind Font-Einbettungen und ähnliche Elemente die zur Ästhetik/Branding von allen Webseiten gehören, nicht möglich. Mit 4G Flatrate und Glasfaseranschluss beinahe als Regel macht es keinen Sinn, unsere Webseite für diesen Markt zu optimieren. (Bei vielen Unternehmenswebseiten passieren ähnliche Probleme)

Versuch doch mal den Opera Mobile Browser, anstelle des Minis. Dort funktionieren die Schriften meistens, auch wenn nicht immer alles richtig (Icons z.B.)

Im September gibts ein Android-Softwareupdate für dein Fairphone auf eine neuere, aber nicht neuste Androidversion. Versuchs dann doch nochmals, vielleicht hilft ja das schon etwas. Der Androidbrowser war eher bei älteren Geräten in Verwendung. Bei den meisten neueren Androidgeräten ist Chrome der Standard.

Gemessen an der Statistik sind die einzigen Androidbrowser- und Operabesucher vermutlich du :D
