### ISSUE TITLE
Mailversand wenn ausgeloggt nicht möglich

### ISSUE THREAD

**Issue by jamiedee** [sxwid/admidio3.1_scoutversion#4]
Kannst du noch die Fehlerbehebung hier publizieren, damit man auch als Besucher dem Webmaster Mails senden kann? Du hast ja dies mal geändert hier früher, ist aber inzwischen überschrieben geworden.

**Comment by sxwid** [comment]
hää, wo ist denn mein commit hin? es ist echt nicht mehr da. voll hoholo. i repeat
edit: fixed with commit 5f04827415e34846ce8a1f5ccb782e47aef02379

**Comment by jamiedee** [comment]
hmm ich glaub du hast lokal ein commit gemacht aber nicht gesynct? aber jetzt ist gut!
