### ISSUE TITLE
Darstellungsfehler Fotoalbum

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#5]
Im Fotoalbum wird das 1. Bild auf der 2. Zeile nicht dargestellt? Ausserdem sind die Bilder teilweise nicht gleich gross (oder ist das ein Feature, not a Bug?)
![unbenannt](https://cloud.githubusercontent.com/assets/13117378/14241645/bef4ce9a-fa4c-11e5-9555-e6630b2dadd7.PNG)

**Comment by jamiedee** [comment]
Ja ist mehr eine Zwischenlösung mittels CSS mit dem Hintergedanken, dass alle Fotos im Album so die gleiche Höhe aufweisen, egal ob Hoch- oder Querformat. In der Regel sollte dies auch funktionieren, da selten mit unterschiedlichen Proportionen fotografiert wird (meistens 4:3, 3:2 oder 16:9, wobei man selten diese Proportion wechseln wird, während einer Aktivität)
Meine Fotos sind meistens mit 3:2, deshalb funktioniert dann dies auch recht gut:

![bildschirmfoto 2016-04-04 um 12 37 35](https://cloud.githubusercontent.com/assets/2400979/14244256/c96ab82e-fa62-11e5-860e-94cd6393815f.png)

Bei der Übersicht über alle Alben hab ich aber eingestellt, dass hochformatige Bilder skaliert werden zu einem querformatigen Bild. Nur in der Ansicht eines spezifischen Albums nicht.

![bildschirmfoto 2016-04-04 um 12 43 28](https://cloud.githubusercontent.com/assets/2400979/14244310/0f042974-fa63-11e5-9a01-6ca6ec036264.png)

Denkst du dies würde so meistens funktionieren? Du hast halt gerade eine ziemliche Mischung an Bilder hochgeladen. So was würde man ja selten machen?

**Comment by sxwid** [comment]
ach so, ok. nun, dann ist easy. ich dachte nur ich checks mal. aber wenn laut deinem ersten bild funktionierts ja recht gut. ausser man würde fotos vor dem upload zuschneiden. das hab ich schon ein, zwei male gmachet... aber sonst kannst du es schliessen und wir sehen ob bug meldungen kommen von den endusern :)

**Comment by jamiedee** [comment]
hab auch ab und zu etwas zugeschnitten. vielleicht wenn man darauf schaut, dass die Proportionen gleich bleiben beim zuschneiden, gibts kein Problem.

Aber ja ist auch momentan nicht so eine glückliche Lösung. Aber ist recht schwierig hoch- und querformatige Bilder über CSS anzusprechen, ohne dass diese überhaupt eine andere class oder id haben und gleichzeitig automatisch sich skalieren je nach browsergrösse.

Evtl. könnt ich mit mehreren Fixbreiten arbeiten via media queries. Momentan stimmt es optisch bei der mobile ansicht auch nicht wirklich. Vielleicht ist dort besser nur einspaltig.

**Comment by sxwid** [comment]
nun - meine meinung ist, dass es kein issue ist und eventuell als enhancement für milestone 1.5 aufgenommen werden soll... einverstanden?

**Comment by jamiedee** [comment]
die mobile Fotoansicht ist schon etwas übel.. vielleicht vers. 1.01?

**Comment by jamiedee** [comment]
masonry oder grid einbauen

**Comment by jamiedee** [comment]
Alle Bilder werden nun auf gleiche Höhe skaliert.
