### ISSUE TITLE
Mitglieder zuordnen Grafik

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#7]
noch falscher Pfeil da...
![unbenannt](https://cloud.githubusercontent.com/assets/13117378/14244213/35fbabbe-fa5a-11e5-9542-4ee4c537eeb2.PNG)

**Comment by jamiedee** [comment]
Ja, der Teil «Mitgliederzuordnung» ist nur für Webmaster sichtbar. Ich hab mich bei der Gestaltung vorläufig auf Sachen beschränkt, die Besucher, Teilnehmer oder normale Leiter sehen. Vielleicht in der Zukunft?
Der unschöne Dropdownpfeil ist von Firefox, oder?

**Comment by sxwid** [comment]
ok, spielt imho auch keine rolle - ich hab auch nicht alles wunderbar perfekt mir vorgestellt - wir müssen auch ein bisschen aufwand/ertrag abschätzen...

**Comment by jamiedee** [comment]
ich habs mal deshalb ins Milestone für die Version 1.5 genommen;)
Version 1 = Website online, 1.5 = Added Features und Bugs ;)

**Comment by sxwid** [comment]
added bugs? ;) hoffentlich nicht :8ball:

**Comment by jamiedee** [comment]
konnte es dann doch nicht lassen ;) siehe commit oben
