### ISSUE TITLE
Menu Mobile

### ISSUE THREAD

**Issue by sxwid** [sxwid/admidio3.1_scoutversion#8]
Ist es gewollt, dass das mobile Menu jeweils unter dem Seitentitel und den Menufunktionen erscheint? Wäre es nicht logischer ganz zu oberst?

**Comment by jamiedee** [comment]
Je nach dem. War zu kompliziert das Admidio-Mobile-Menü auseinander zu nehmen und den Seitentitel und die Seitenfunktionen von den verschiedenen Seiten zu trennen, da alles miteinander verbunden ist.

Finde das Mobile Menu nicht den optischsten Hit, aber funktioniert so meistens ausreichend. Das gesamte Mobile-Konzept bedürfte etwas Bearbeitung. Aber so essentiell ist das nicht und würde zu viel Zeit in Anspruch nehmen.
