### ISSUE TITLE
Aktivitäten: Leitermail-Knopf fehlt?

### ISSUE THREAD

**Issue by jamiedee** [sxwid/admidio3.1_scoutversion#9]
Bin mir nicht sicher, ob dass an was anderem liegt, aber fehlt bei den Aktivitäten nicht der Leitermail-Knopf?

![bildschirmfoto 2016-04-04 um 12 14 39](https://cloud.githubusercontent.com/assets/2400979/14244734/58585026-fa65-11e5-898f-11cb26042eeb.png)

**Comment by sxwid** [comment]
ich hab das so gelöst, dass mit den checkbox ausgewählt werden kann. oh - du hast die checkboxes global ausgeblendet. das geht natürlich nicht. dann machen wir das rückgängig (#issue2) und ich versuch trotzdem das im code auszublenden
ich dachte, weniger buttons ist schöner...

**Comment by jamiedee** [comment]
Nein, ich hab sie bei #2 nur ausgeblendet wenn man eine neue Nachricht schreibt. Wo wären die sonst dargestellt? Die E-Mail an Leiter Funktion sollte dadurch nicht betroffen sein.

**Comment by sxwid** [comment]
Das problem ist, dass die Leitermailfunktion auch aus der Datei message_write.php kommt... das geht daher nicht... ich muss also versuchen, zu unterscheiden, ob man von der Seite Dates kommt oder Messages...

**Comment by jamiedee** [comment]
Achso, du hast den Knopf E-Mail an Leiter aus der Aktivitätenseite genommen und erst beim E-Mail schreiben die Auswahlmöglichketi Leiter/TN gemacht? Ok. Ich ändere das CSS wieder.

**Comment by sxwid** [comment]
genau so. mmh. ich such mal schnell..

**Comment by sxwid** [comment]
so, ich habs glaub ich gefixed. Nun passiert folgendes:
--> Checkboxes kommen nur bei Terminen
--> wird nichts angekreuzt ODER beides, so wird die Mail an Leiter und TN versandt. 
--> ist nur eine Option aktiviert, so geht die Nachricht an TN oder Leiter
commit b85da3e6fe6f277a489fb54c7e231ee147053aac
